### ISSUE TITLE
Email address

### ISSUE THREAD

**Issue by CoralineAda** [simonv3/covenant-generator#1]
The new version of Contributor Covenant (1.3.0) requires the insertion of an email address in the document. Could this be added as a parameter?

**Comment by simonv3** [comment]
@CoralineAda Done in https://github.com/simonv3/covenant-generator/commit/d93d365feaf9a1a4f621d234877b44afdb12ae7c. Let me know if that's what you had in mind. (and it's been published to NPM https://www.npmjs.com/package/covgen)

It might be an idea for the future to also specify a specific version - which I guess is the point of making it semantic versioned.

**Comment by CoralineAda** [comment]
Forgive my lack of node knowledge… does this commit handle injecting the email address into the CoC?

**Comment by simonv3** [comment]
Sorry! That commit doesn't specifically (the relevant code is here: https://github.com/simonv3/covenant-generator/blob/master/covenant.js#L34). That commit is just the most recent version with better instructions when command gets run. I guess that wasn't a very useful link.

Now running `covgen <email address>` will replace `[INSERT EMAIL ADDRESS]` with whatever you typed in place of `<email address>` and running covgen without the email address will tell you to add an e-mail address.

**Comment by CoralineAda** [comment]
Perfect! Let me know when this is merged and I will add this to the site.

**Comment by simonv3** [comment]
Done :)

**Comment by simonv3** [comment]
It's merged :)

**Comment by CoralineAda** [comment]
I tried this and got an empty CODE_OF_CONDUCT.md file...

**Comment by simonv3** [comment]
Boo. Let me see if I can replicate that.

**Comment by simonv3** [comment]
@CoralineAda I've just updated it. You'll need to install it again (`npm install -g covgen`) to get the most up to date version. 

It was happening occasionally for me too, just not every time, which is why I didn't catch it - I was using the standard `http` library to download the text, and that may just not have been robust enough to handle the download. I've switched to `request` and pretty much changed the entire code around the downloading. I've tried it in a couple of places now and it looks like it's downloading every time. Can you try again?

**Comment by CoralineAda** [comment]
It works! I’ve linked it from the main page. Great work!

**Comment by simonv3** [comment]
Huzzah! Thanks :)
